### ISSUE TITLE
Show Lokasi

### ISSUE THREAD

**Issue by widoyo** [rpahlevy/pbase-cloud#1]
https://github.com/rpahlevy/pbase-cloud/blob/a19935b76446247ff93309d7bb4ec1964e31c883/src/lokasi.php#L62

Show (detail) Lokasi perlu menampilkan:
Lebih baik beberapa data di halaman ini generated, simpan ke redis:

1. Tentang data teknis lokasi: {nama lokasi, elevasi (ketinggian thd permukaan air laut), jenis lokasi pos (PCH (pos Cuah Hujan), PDA (Pos Duga Air), Klimatologi)
2. Data periodik berupa 
  2.1 Chart (TMA: Line Chart, Hujan: Bar/Column chart) selama `periode` (saat ini diset 3 bulan), terdapat navigasi maju-mundur sesuai `periode`
  2.2 Ringkasan data: {waktu data terakhir, banyak record data, persentase banyak data terhadap banyak data yang seharusnya}
3. Logger, logger mana saja yang pernah duduk di lokasi ini dan masing-masing berapa banyak kontribusi datanya

**Comment by rpahlevy** [comment]
Need to use redis
