### ISSUE TITLE
Tambahkan Fungsi Download untuk Data per 24 jam

### ISSUE THREAD

**Issue by widoyo** [rpahlevy/pbase-cloud#10]
Dasarnya sama dengan #9 

Tambahkan pilihan Download: 24 jam

1. Untuk Curah Hujan: jumlahkan dari jam 7 pagi hingga jam 6:55 (hari berikutnya)
2. Untuk TMA, sama dengan versi per 1 jam

**Comment by rpahlevy** [comment]
untuk perhitungan 24 jam TMA pengambilan datanya bagaimana ya pak?
apakah seperti ini : 2020-04-06 -> dari 2020-04-05 00:00 sampai 2020-04-05 23:55

**Comment by widoyo** [comment]
On Mon, 6 Apr 2020, 12:03 Rio Pahlevy, <notifications@github.com> wrote:

> untuk perhitungan 24 jam TMA pengambilan datanya bagaimana ya pak?
> apakah seperti ini : 2020-04-06 -> dari 2020-04-05 00:00 sampai 2020-04-05
> 23:55
>
Artinya data tgl 2020-04-05. Keluarnnya nilai Min, Max, dam Rerata dalam
rentang waktu tersebut

**Comment by rpahlevy** [comment]
fixed on [225bf36](https://github.com/rpahlevy/pbase-cloud/commit/225bf36a29a408773f3ef07804793b29b74b00f6) and deployed to dev-io
