### ISSUE TITLE
Logger Sehat isinya '0 Ada Kendala?

### ISSUE THREAD

**Issue by widoyo** [rpahlevy/pbase-cloud#3]
https://github.com/rpahlevy/pbase-cloud/blob/a19935b76446247ff93309d7bb4ec1964e31c883/src/logger.php#L106

Bila perlu content banyak data generated, masuk ke redis

**Comment by rpahlevy** [comment]
untuk yg di id.prinus masih 0 krn blm generate tabel periodik
kalau yg di dev-io sudah ada nilainya pak

**Comment by widoyo** [comment]
Aplikasi dan data untul PBase yang lebih terkini: dev-io.prinus.net
