### ISSUE TITLE
Chart Curah hujan / TMA

### ISSUE THREAD

**Issue by widoyo** [rpahlevy/pbase-cloud#43]
id.prinus.net
URL: /logger/2009-1
Chart curah hujan ganti menjadi warna Biru, skala 0-200 mm (sudah OK), Berikan Judul: Curah Hujan

Chart SQ dipindahkan ke bawah, SQ punya skala 0 - 30

Demikian pula untuk TMA, chart SQ diikutkan ke chart bawahnya. Jika tidak memungkinkan line dan bar/column jdi satu, boleh ganti chart dengan ChartJs.

**Comment by rpahlevy** [comment]
Pak @widoyo untuk yg chart DISTANCE apakah tetap bersama SQ dan BATT?
yg berarti akan ada 2 chart seperti ini?

1. Chart Curah Hujan (jika tipe logger arr / klimat)
2. Chart gabungan (SQ:bar, BATT:line, DISTANCE:line)

**Comment by widoyo** [comment]
Distance terpisah seperti tick
