### ISSUE TITLE
Tambahkan Fungsi Download untuk data per 1 jam

### ISSUE THREAD

**Issue by widoyo** [rpahlevy/pbase-cloud#9]
Dasarnya seperti #8 .

Tambahkan pilihan download: 5 Menit | 1 Jam
1. Untuk curah hujan data per 5 menitan dijumlahkan
2. Untuk TMA data diambil nilai Min, Max (banyak kolom berbeda dibanding 5 menitan) pada jam tsb.

**Comment by rpahlevy** [comment]
pengambilan datanya apakah benar seperti ini pak @widoyo 
1. 03:00 = data dari 02:05 -> 03:00
2. 2020-04-06 00:00 = data dari 2020-04-05 23:05 -> 2020-04-06 00:00

**Comment by widoyo** [comment]
Keterangan itu utk Hujan, nilai Rain dijumlahkan.

Utk TMA: rentang jam sama, diambil nilai min, max, rerata

**Comment by rpahlevy** [comment]
fixed on [225bf36](https://github.com/rpahlevy/pbase-cloud/commit/225bf36a29a408773f3ef07804793b29b74b00f6) and deployed to dev-io
